240124 BFS 노영호 제출합니다.
wannaseoji/AlgorithmStudy pull request #9
Opened 2024-01-24 06:24 UTC by bluessomYH

BOJ_2194 : 유닛 이동시키기
BOJ_10917 : Your life
BOJ_25516 : 거리가 k이하인 트리 노드에서 사과 수확하기

2024-01-27 00:41 UTC, seohyunkwon requested changes
코드 잘 봤습니다 !

2024-01-27 00:41 UTC, seohyunkwon commented on youngho/BOJ/Jan_24/BOJ_10917.java
> +        System.out.println(bfs(1));
bfs 메서드 리턴값을 int로 설정해서 깔끔하게 출력하셨네요 배워갑니다~!

2024-01-27 06:30 UTC, bluessomYH commented on youngho/BOJ/Jan_24/BOJ_25516.java
> +			tree[b].add(a);
오 그러네요 단방향 연결이란 걸 생각하지 못했었네요. 감사합니다!!

2024-01-27 10:57 UTC, jiyoung-Heo commented
확인 했습니다 ! 
중간중간 주석이 있어서 보기 편한 것 같아요 👍
이번주도 고생하셨습니다!

2024-01-28 01:28 UTC, wannaseoji reviewed
확인했습니다. 한수 배워갑니다.

2024-01-28 05:35 UTC, junseok-99 commented
확인했습니다.
이번 주도 고생 많으셨어요!

2024-01-28 06:38 UTC, merged